image: fedora:latest

before_script:
  - dnf install -y curl make awscli
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz > /tmp/hugo.tar.gz
  - tar xvzf /tmp/hugo.tar.gz hugo 
  - mv hugo /usr/bin/hugo
  - hugo version
  - aws --version
  - make --version

upgrade:
  script:
    - echo "SITE_URL=$SITE_URL" >> prod.env
    - echo "CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID" >> prod.env
    - make deploy
