baseurl                  = "https://asm.io/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Alex Metzger"
theme                    = "sam"
pygmentsStyle            = "manni"
pygmentsCodefences       = true
enableRobotsTXT = false
disableHugoGeneratorInject = true
ignoreFiles = [ "\\.gitkeep$" ]

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    title                = "Alex Metzger"
    description          = "Alex Metzger's personal site"
    images               = ["img/tc.png"]

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/toys"
    text = "toys"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[imaging]
    quality = 75
