languageCode = "en-us"
title = "Alex Metzger"
baseurl = "https://asm.io/"
theme = "aerial"
enableRobotsTXT = false
disableHugoGeneratorInject = true
disableKinds = [ "page", "section", "taxonomy", "taxonomyTerm", "RSS" ]
googleAnalytics = "UA-71888221-1"
ignoreFiles = [ "\\.gitkeep$" ]

[params]
  name = "Alex Metzger"
  about = "Software Enthusiast &nbsp;&bull;&nbsp; Experienced Typist &nbsp;&bull;&nbsp; Computer Owner"
  description = "Alex Metzger"
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Emoji"
  icon = "smile-o"
  link = "https://asm.io/emoji"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/metzger"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/emptycupofrum"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/ametzger"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/asmetzger"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:asm@asm.io?subject=I love your website&body=Howdy, I just wanted to say your website is incredible"
