baseurl = "https://asm.io"
title = "Alex Metzger"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = false
disableHugoGeneratorInject = true
ignoreFiles = [ "\\.gitkeep$" ]

[params]
    author = "Alex Metzger"
    description = "The personal website and blog of Alex Metzger"
    keywords = "blog,developer,devops,personal"
    info = "Developer • Cloud Wrangler • Computer Enthusiast"
    avatarurl = "img/avatar.jpg"
    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/ametzger/asm.io/tree/"

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ametzger"
[[params.social]]
    name = "GitLab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/ametzger"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/metzger"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 4
    url = "https://www.instagram.com/emptycupofrum"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/asmetzger/"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    weight = 6
    url = "https://keybase.io/asm"


[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[menu.main]]
name = "About"
weight = 3
url = "about/"

[[menu.main]]
name = "Contact"
weight = 4
url = "contact/"
