#!/usr/bin/env bash
set -e

source .env

echo "generating site"

script/generate

echo "generated, pushing to S3"

aws s3 sync public s3://asm.io # --delete # don't remove files in the S3 bucket but not local

echo "synced to S3, invalidating cloudfront distribution $ASM_IO_DISTRIBUTION_ID"

aws cloudfront create-invalidation --distribution-id=$ASM_IO_DISTRIBUTION_ID --paths "/*"

echo "done"
